spring.application.name=AI-Enhanced-LMS-backend


server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ai_lms_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#SERP API
serpapi.api.key=b21e6768b7d0c017f7c89cc144ae90dd6c3f9856dbdab0f9709ab9963491c6d9
serpapi.base.url=https://serpapi.com/search.json